language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
    - oracle-java8-installer
    - docker-ce

cache:
  directories:
    - $HOME/.m2

sudo: false

#services:
#  - docker

install: true

script:
  - "sudo service docker start"
  - "docker --version"
  - "mvn clean dependency:list test -Pall-dbs -Dsort -U"
